import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "../component/home/header"
import Section from "../component/home/section"
import OurFeaturedBrands from "../component/home/our"
import BrowseCategories from "../component/home/browse"
import TrendingProducts from "../component/home/trending"
import Taking from "../component/home/taking"
import Apple from "../component/home/apple"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <Section/>
        <OurFeaturedBrands/>
        <BrowseCategories/>
        <TrendingProducts/>
        <Taking/>
        <Apple/>
      </main>
    </>
  )
}
